all:
	g++ -std=c++0x main.cpp ModelParse.cpp ModelData.cpp ModelEntity.cpp ModelName.cpp ModelNormal.cpp ModelTexture.cpp ModelTriangle.cpp ModelVertice.cpp PPM.cpp -lGL -lGLU -lGLEW -lglut -o ./build/main
